---
title: "Reports - Exploratory"
author: "irw"
output: html_document
editor_options: 
  chunk_output_type: console
params:
  verbose: yes
---

<!-- Children -->
```{r, child=here::here("02-reports/example-1/analysis/00-import.Rmd")}
```
<!-- End Children-->

```{r, include=FALSE}
if (params$verbose) {
  knitr::opts_chunk$set(
    echo = TRUE,
    warning = TRUE,
    message = TRUE
  )
} else {
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE
  )
}
```

```{r}
# Load libraries
library(tidyverse)
library(here)
library(emmeans)
```


```{r}
iris_data %>% 
  ggplot(aes(x = Species, y = Sepal.Length)) +
  geom_boxplot()

iris_data %>% 
  ggplot(aes(x = Species, y = Sepal.Width)) +
  geom_boxplot()

iris_data %>% 
  ggplot(aes(x = Species, y = Petal.Length)) +
  geom_boxplot()

iris_data %>% 
  ggplot(aes(x = Species, y = Petal.Width)) +
  geom_boxplot()
```

```{r}
contrasts(iris_data$Species) <- contr.sum

model_sepal_length <- lm(iris_data, formula = Sepal.Length ~ Species)
model_sepal_length %>% summary()
attributes(model_sepal_length$qr$qr)$contrasts

model_sepal_width <- lm(iris_data, formula = Sepal.Width ~ Species) 
model_sepal_width %>% summary()
attributes(model_sepal_width$qr$qr)$contrasts

model_petal_length <- lm(iris_data, formula = Petal.Length ~ Species)
model_petal_length %>% summary()
attributes(model_petal_length$qr$qr)$contrasts

model_petal_width <- lm(iris_data, formula = Petal.Width ~ Species)
model_petal_width %>% summary()
attributes(model_petal_width$qr$qr)$contrasts
```

```{r}
check_emm <- function(model) {
  emm_model <- emmeans(model, "Species")
  pairs(emm_model) %>% print()
  cat("\n --- \n")
  
  coef(pairs(emm_model)) %>% print()
  cat("\n --- \n")
  
  pwpm(emm_model) %>% print()
  cat("\n --- \n")
  
  (plot(emm_model, comparisons = TRUE) + theme_bw()) %>% print()
  
  (pwpp(emm_model) + theme_bw()) %>% print()
}

model_sepal_length %>% check_emm()
model_sepal_width %>% check_emm()
model_petal_length %>% check_emm()
model_petal_width %>% check_emm()
```

